---
- name: Install
  hosts: localhost
  vars:

    connection: local
    sudo: yes
    tasks:
    - name: download alpha-stack repo
    - git:
      repo: ssh://git@github.com/alpha-stack/alpha-stack.git
      dest: /opt/alpha-stack/
      version:
